[0m11:50:21.390584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5ab27e7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5aa208250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5aa2081f0>]}


============================== 11:50:21.393028 | 9c896048-ce65-4063-9c8a-ea57be7c9f4b ==============================
[0m11:50:21.393028 [info ] [MainThread]: Running with dbt=1.10.3
[0m11:50:21.393488 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/developer/workspace/dbt-elt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:50:37.151750 [debug] [MainThread]: Starter project path: /home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/dbt/include/starter_project
[0m11:50:37.153830 [info ] [MainThread]: 
Your new dbt project "dbt_lakehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:50:37.156415 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 15.807236, "process_in_blocks": "7560", "process_kernel_time": 0.031705, "process_mem_max_rss": "88828", "process_out_blocks": "72", "process_user_time": 0.891723}
[0m11:50:37.157121 [debug] [MainThread]: Command `dbt init` succeeded at 11:50:37.156846 after 15.81 seconds
[0m11:50:37.158341 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5ab27e7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5aa1f2d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5aa1f2220>]}
[0m11:50:37.159604 [debug] [MainThread]: Flushing usage events
[0m11:50:37.932618 [debug] [MainThread]: An error was encountered while trying to flush usage events
