[0m11:50:21.390584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5ab27e7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5aa208250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5aa2081f0>]}


============================== 11:50:21.393028 | 9c896048-ce65-4063-9c8a-ea57be7c9f4b ==============================
[0m11:50:21.393028 [info ] [MainThread]: Running with dbt=1.10.3
[0m11:50:21.393488 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/developer/workspace/dbt-elt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:50:37.151750 [debug] [MainThread]: Starter project path: /home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/dbt/include/starter_project
[0m11:50:37.153830 [info ] [MainThread]: 
Your new dbt project "dbt_lakehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:50:37.156415 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 15.807236, "process_in_blocks": "7560", "process_kernel_time": 0.031705, "process_mem_max_rss": "88828", "process_out_blocks": "72", "process_user_time": 0.891723}
[0m11:50:37.157121 [debug] [MainThread]: Command `dbt init` succeeded at 11:50:37.156846 after 15.81 seconds
[0m11:50:37.158341 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5ab27e7c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5aa1f2d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5aa1f2220>]}
[0m11:50:37.159604 [debug] [MainThread]: Flushing usage events
[0m11:50:37.932618 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:13:19.953937 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21ea4cd7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21e9456160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21e9456100>]}


============================== 20:13:19.956734 | ebf86db3-37e7-4134-a18b-87341079fceb ==============================
[0m20:13:19.956734 [info ] [MainThread]: Running with dbt=1.10.3
[0m20:13:19.957199 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/developer/workspace/dbt-elt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:13:25.787688 [error] [MainThread]: Encountered an error:

[0m20:13:25.792413 [error] [MainThread]: Traceback (most recent call last):
  File "/home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/dbt/task/init.py", line 324, in run
    project_name = self.get_valid_project_name()
  File "/home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/dbt/task/init.py", line 278, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "/home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m20:13:25.795467 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 5.882609, "process_in_blocks": "77672", "process_kernel_time": 0.074342, "process_mem_max_rss": "88624", "process_out_blocks": "24", "process_user_time": 0.896127}
[0m20:13:25.797236 [debug] [MainThread]: Command `dbt init` failed at 20:13:25.796950 after 5.88 seconds
[0m20:13:25.798374 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21ea4cd7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21e9456220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f21e9456f40>]}
[0m20:13:25.799493 [debug] [MainThread]: Flushing usage events
[0m20:13:26.245231 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:14:27.859581 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x725a203cd880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x725a1f356160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x725a1f356100>]}


============================== 20:14:27.862067 | 5b0fe76e-3d78-438a-84b4-3f8bfef4f07d ==============================
[0m20:14:27.862067 [info ] [MainThread]: Running with dbt=1.10.3
[0m20:14:27.862544 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/developer/workspace/dbt-elt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:14:38.432427 [debug] [MainThread]: Starter project path: /home/developer/anaconda3/envs/loggiutilenv/lib/python3.9/site-packages/dbt/include/starter_project
[0m20:14:38.439092 [info ] [MainThread]: 
Your new dbt project "dbt_lakehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:14:38.441550 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 10.623185, "process_in_blocks": "128", "process_kernel_time": 0.045062, "process_mem_max_rss": "88268", "process_out_blocks": "80", "process_user_time": 0.888224}
[0m20:14:38.443314 [debug] [MainThread]: Command `dbt init` succeeded at 20:14:38.442992 after 10.63 seconds
[0m20:14:38.444439 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x725a203cd880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x725a1f340af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x725a1f3403a0>]}
[0m20:14:38.445480 [debug] [MainThread]: Flushing usage events
[0m20:14:38.985827 [debug] [MainThread]: An error was encountered while trying to flush usage events
