[2025-07-05T09:43:37.687+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-05T09:43:37.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lakehouse_pipeline.bronze_to_silver manual__2025-07-05T09:43:36.039222+00:00 [queued]>
[2025-07-05T09:43:37.713+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lakehouse_pipeline.bronze_to_silver manual__2025-07-05T09:43:36.039222+00:00 [queued]>
[2025-07-05T09:43:37.713+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-05T09:43:37.720+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): bronze_to_silver> on 2025-07-05 09:43:36.039222+00:00
[2025-07-05T09:43:37.726+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lakehouse_pipeline', 'bronze_to_silver', 'manual__2025-07-05T09:43:36.039222+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpx3k4mtar']
[2025-07-05T09:43:37.727+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask bronze_to_silver
[2025-07-05T09:43:37.728+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-05T09:43:37.728+0000] {standard_task_runner.py:63} INFO - Started process 209 to run task
[2025-07-05T09:43:37.755+0000] {task_command.py:426} INFO - Running <TaskInstance: lakehouse_pipeline.bronze_to_silver manual__2025-07-05T09:43:36.039222+00:00 [running]> on host 29ea1cae8d3a
[2025-07-05T09:43:37.804+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lakehouse_pipeline' AIRFLOW_CTX_TASK_ID='bronze_to_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-05T09:43:36.039222+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-05T09:43:36.039222+00:00'
[2025-07-05T09:43:37.804+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-05T09:43:37.930+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-05T09:43:37.931+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bronze_to_silver.py", line 10, in run
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 106, in launch_gateway
    raise RuntimeError("Java gateway process exited before sending its port number")
RuntimeError: Java gateway process exited before sending its port number
[2025-07-05T09:43:37.950+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=lakehouse_pipeline, task_id=bronze_to_silver, run_id=manual__2025-07-05T09:43:36.039222+00:00, execution_date=20250705T094336, start_date=20250705T094337, end_date=20250705T094337
[2025-07-05T09:43:37.966+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task bronze_to_silver (Java gateway process exited before sending its port number; 209)
[2025-07-05T09:43:37.982+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-05T09:43:38.010+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-05T09:43:38.013+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
